import { DailyQuest, LeaderboardUser, PathUnit } from '../types';

export const DUO_UNITS: PathUnit[] = [
  {
    id: 'unit_1',
    unitNumber: 1,
    titleAr: 'عالم الأعداد والعد البصري',
    titleEn: 'Numbers & Visual Counting',
    subtitleAr: 'تعلم عد الأشياء والتعرف على الأرقام حتى 10',
    subtitleEn: 'Count objects & recognize numbers up to 10',
    themeColor: 'emerald',
    gradientBg: 'from-emerald-500 to-teal-600',
    bannerEmoji: '🍎',
    chestReward: {
      id: 'chest_unit_1',
      gems: 25,
      stars: 5,
      titleAr: 'صندوق بطل العدّ الأسطوري',
      titleEn: 'Legendary Counting Chest',
    },
    lessons: [
      {
        id: 'u1_l1',
        unitId: 'unit_1',
        titleAr: 'عدّ الأشياء من 1 إلى 5',
        titleEn: 'Counting 1 to 5',
        descriptionAr: 'ابدأ بعد التفاح والألعاب الممتعة',
        descriptionEn: 'Start by counting fun items and toys',
        icon: '🔢',
        color: 'emerald',
        xpReward: 15,
        starsRequiredToUnlock: 0,
        questions: [
          {
            id: 'u1_l1_q1',
            type: 'visual_count',
            questionAr: 'كم عدد التفاحات في الصورة؟',
            questionEn: 'How many apples are there?',
            visualCount: 3,
            itemThemeId: 'apple',
            options: [2, 3, 4],
            correctAnswer: 3,
            explanationAr: 'هناك 3 تفاحات لذيذة 🍎🍎🍎',
            explanationEn: 'There are 3 delicious apples 🍎🍎🍎',
          },
          {
            id: 'u1_l1_q2',
            type: 'multiple_choice',
            questionAr: 'اختر الرقم الذي يمثل: ⭐ ⭐ ⭐ ⭐',
            questionEn: 'Choose the number representing: ⭐ ⭐ ⭐ ⭐',
            options: [3, 4, 5],
            correctAnswer: 4,
            explanationAr: 'العدد هو 4 نجوم لامعة!',
            explanationEn: 'The number is 4 shiny stars!',
          },
          {
            id: 'u1_l1_q3',
            type: 'true_false',
            questionAr: 'هل عدد السيارات 🚗 🚗 هو 2؟',
            questionEn: 'Is the number of cars 🚗 🚗 equal to 2?',
            options: ['نعم / True', 'لا / False'],
            correctAnswer: 'نعم / True',
            explanationAr: 'نعم بالتأكيد! توجد سيارتان 🚗 🚗',
            explanationEn: 'Yes! Exactly 2 cars 🚗 🚗',
          },
          {
            id: 'u1_l1_q4',
            type: 'match_pairs',
            questionAr: 'طابق بين الصورة والعدد المناسب:',
            questionEn: 'Match each picture with its number:',
            correctAnswer: 'matched_all',
            matchingPairs: [
              { id: 'p1', left: '🍬', right: '1' },
              { id: 'p2', left: '🍬 🍬', right: '2' },
              { id: 'p3', left: '🍬 🍬 🍬', right: '3' },
            ],
            explanationAr: 'تطابق رائع وذكي!',
            explanationEn: 'Brilliant matching!',
          },
          {
            id: 'u1_l1_q5',
            type: 'visual_count',
            questionAr: 'ما هو إجمالي عدد الكرات ⚽؟',
            questionEn: 'What is the total number of balls ⚽?',
            visualCount: 5,
            itemThemeId: 'ball',
            options: [4, 5, 6],
            correctAnswer: 5,
            explanationAr: 'ممتاز! 5 كرات كاملة ⚽⚽⚽⚽⚽',
            explanationEn: 'Super! 5 full balls ⚽⚽⚽⚽⚽',
          },
        ],
      },
      {
        id: 'u1_l2',
        unitId: 'unit_1',
        titleAr: 'الأعداد من 6 إلى 10 ومقارنتها',
        titleEn: 'Numbers 6 to 10 & Comparisons',
        descriptionAr: 'استكشف الأعداد الأكبر وتعلم المقارنة',
        descriptionEn: 'Explore larger numbers and comparisons',
        icon: '🔟',
        color: 'teal',
        xpReward: 20,
        starsRequiredToUnlock: 1,
        questions: [
          {
            id: 'u1_l2_q1',
            type: 'visual_count',
            questionAr: 'كم عدد الكب كيك 🧁 اللذيذة؟',
            questionEn: 'How many yummy cupcakes 🧁 are there?',
            visualCount: 7,
            itemThemeId: 'cupcake',
            options: [6, 7, 8],
            correctAnswer: 7,
            explanationAr: 'رائع! 7 قطع كب كيك شهية!',
            explanationEn: 'Great! 7 sweet cupcakes!',
          },
          {
            id: 'u1_l2_q2',
            type: 'multiple_choice',
            questionAr: 'أي من الأعداد التالية هو الأكبر؟',
            questionEn: 'Which of the following numbers is the largest?',
            options: [4, 7, 9],
            correctAnswer: 9,
            explanationAr: 'العدد 9 هو الأكبر بين الخيارات!',
            explanationEn: 'Number 9 is the largest among the options!',
          },
          {
            id: 'u1_l2_q3',
            type: 'fill_blank',
            questionAr: 'أكمل تسلسل الأعداد: 6 ، 7 ، [ ؟ ] ، 9',
            questionEn: 'Complete the sequence: 6 , 7 , [ ? ] , 9',
            options: [8, 5, 10],
            correctAnswer: 8,
            explanationAr: 'العدد الناقص هو 8 بعد 7 وقبل 9!',
            explanationEn: 'The missing number is 8!',
          },
          {
            id: 'u1_l2_q4',
            type: 'true_false',
            questionAr: 'هل 10 أكبر من 6؟',
            questionEn: 'Is 10 greater than 6?',
            options: ['نعم / True', 'لا / False'],
            correctAnswer: 'نعم / True',
            explanationAr: 'نعم! العدد 10 أكبر من 6 بأربع وحدات.',
            explanationEn: 'Yes! 10 is greater than 6.',
          },
          {
            id: 'u1_l2_q5',
            type: 'visual_count',
            questionAr: 'كم زهرة 🌸 جميلة في الحديقة؟',
            questionEn: 'How many lovely flowers 🌸 in the garden?',
            visualCount: 8,
            itemThemeId: 'flower',
            options: [7, 8, 9],
            correctAnswer: 8,
            explanationAr: '8 أزهار جميلة ومشرقة!',
            explanationEn: '8 beautiful flowers!',
          },
        ],
      },
      {
        id: 'u1_l3',
        unitId: 'unit_1',
        titleAr: 'تحدي تاج الأعداد (Boss Quiz)',
        titleEn: 'Numbers Crown Challenge (Boss)',
        descriptionAr: 'اختبر مهاراتك وتوج بتاج الوحدة الأولى',
        descriptionEn: 'Test your skills & win the Unit 1 Crown',
        icon: '👑',
        color: 'amber',
        xpReward: 30,
        starsRequiredToUnlock: 3,
        questions: [
          {
            id: 'u1_l3_q1',
            type: 'match_pairs',
            questionAr: 'طابق بين العدد ومجموعة الرموز:',
            questionEn: 'Match the number with the emoji set:',
            correctAnswer: 'matched_all',
            matchingPairs: [
              { id: 'p1', left: '4', right: '⭐⭐⭐⭐' },
              { id: 'p2', left: '6', right: '🍎🍎🍎🍎🍎🍎' },
              { id: 'p3', left: '2', right: '🚗🚗' },
            ],
            explanationAr: 'بطل حقيقي في المطابقة!',
            explanationEn: 'True matching master!',
          },
          {
            id: 'u1_l3_q2',
            type: 'visual_count',
            questionAr: 'كم عدد الأقلام ✏️ في المقلمة؟',
            questionEn: 'How many pencils ✏️ in the case?',
            visualCount: 10,
            itemThemeId: 'pencil',
            options: [8, 9, 10],
            correctAnswer: 10,
            explanationAr: '10 أقلام كاملة! حزمة مثالية ✏️',
            explanationEn: '10 complete pencils! Perfect pack ✏️',
          },
          {
            id: 'u1_l3_q3',
            type: 'multiple_choice',
            questionAr: 'ما هو العدد الذي يسبق الرقم 5 مباشرة؟',
            questionEn: 'Which number comes directly before 5?',
            options: [3, 4, 6],
            correctAnswer: 4,
            explanationAr: 'العدد 4 يسبق 5 مباشرة (4 ، 5)',
            explanationEn: 'Number 4 comes right before 5!',
          },
        ],
      },
    ],
  },

  {
    id: 'unit_2',
    unitNumber: 2,
    titleAr: 'مغامرات الجمع البصري',
    titleEn: 'Visual Addition Adventures',
    subtitleAr: 'اجمع العناصر وكون معادلات سحرية',
    subtitleEn: 'Combine items and create magical equations',
    themeColor: 'sky',
    gradientBg: 'from-sky-500 to-blue-600',
    bannerEmoji: '➕',
    chestReward: {
      id: 'chest_unit_2',
      gems: 35,
      stars: 6,
      titleAr: 'صندوق عباقرة الجمع',
      titleEn: 'Addition Genius Chest',
    },
    lessons: [
      {
        id: 'u2_l1',
        unitId: 'unit_2',
        titleAr: 'جمع الأعداد حتى 5',
        titleEn: 'Addition up to 5',
        descriptionAr: 'تعلم ضم الأشياء وحساب مجموعها',
        descriptionEn: 'Learn to put items together and find sums',
        icon: '➕',
        color: 'sky',
        xpReward: 15,
        starsRequiredToUnlock: 0,
        questions: [
          {
            id: 'u2_l1_q1',
            type: 'multiple_choice',
            questionAr: 'ما ناتج: 2 + 2 = ؟ (🍎🍎 + 🍎🍎)',
            questionEn: 'What is 2 + 2 = ? (🍎🍎 + 🍎🍎)',
            options: [3, 4, 5],
            correctAnswer: 4,
            num1: 2,
            num2: 2,
            operation: '+',
            explanationAr: '2 تفاحتان + 2 تفاحتان = 4 تفاحات!',
            explanationEn: '2 apples + 2 apples = 4 apples!',
          },
          {
            id: 'u2_l1_q2',
            type: 'equation_build',
            questionAr: 'ابنِ المعادلة الصحيحة: 3 + 1 = 4',
            questionEn: 'Build the correct equation: 3 + 1 = 4',
            equationPieces: ['3', '+', '1', '=', '4'],
            targetEquation: ['3', '+', '1', '=', '4'],
            correctAnswer: '3+1=4',
            explanationAr: 'معادلة مبنية بشكل ممتاز: 3 + 1 = 4',
            explanationEn: 'Equation perfectly built: 3 + 1 = 4',
          },
          {
            id: 'u2_l1_q3',
            type: 'visual_count',
            questionAr: 'لديك 3 سيارات 🚗🚗🚗 وأضفنا 2 🚗🚗. كم المجموع؟',
            questionEn: 'You have 3 cars 🚗🚗🚗 and added 2 🚗🚗. What is the total?',
            visualCount: 5,
            itemThemeId: 'car',
            options: [4, 5, 6],
            correctAnswer: 5,
            explanationAr: '3 + 2 = 5 سيارات رائعة!',
            explanationEn: '3 + 2 = 5 cool cars!',
          },
          {
            id: 'u2_l1_q4',
            type: 'true_false',
            questionAr: 'هل 1 + 3 = 4؟',
            questionEn: 'Is 1 + 3 = 4?',
            options: ['نعم / True', 'لا / False'],
            correctAnswer: 'نعم / True',
            explanationAr: 'نعم! 1 + 3 = 4 صحيح 100%',
            explanationEn: 'Yes! 1 + 3 = 4 is 100% correct.',
          },
        ],
      },
      {
        id: 'u2_l2',
        unitId: 'unit_2',
        titleAr: 'مكملات العشرة والجمع السريع',
        titleEn: 'Bonds of 10 & Speedy Addition',
        descriptionAr: 'اكتشف الأعداد التي تكون 10',
        descriptionEn: 'Discover numbers that add up to 10',
        icon: '🔟',
        color: 'blue',
        xpReward: 20,
        starsRequiredToUnlock: 2,
        questions: [
          {
            id: 'u2_l2_q1',
            type: 'fill_blank',
            questionAr: 'ما هو العدد الناقص: 6 + [ ؟ ] = 10',
            questionEn: 'What is the missing number: 6 + [ ? ] = 10',
            options: [3, 4, 5],
            correctAnswer: 4,
            explanationAr: '6 + 4 = 10 (4 هو مكمل 6 للعشرة)',
            explanationEn: '6 + 4 = 10 (4 makes 10 with 6)',
          },
          {
            id: 'u2_l2_q2',
            type: 'match_pairs',
            questionAr: 'طابق كل جمع بناتجه الصحيح:',
            questionEn: 'Match each sum to its result:',
            correctAnswer: 'matched_all',
            matchingPairs: [
              { id: 'p1', left: '5 + 5', right: '10' },
              { id: 'p2', left: '4 + 3', right: '7' },
              { id: 'p3', left: '6 + 2', right: '8' },
            ],
            explanationAr: 'حساب ذهني خارق!',
            explanationEn: 'Super mental math!',
          },
          {
            id: 'u2_l2_q3',
            type: 'multiple_choice',
            questionAr: 'اشترى سامي 4 بالونات 🎈 ثم 5 بالونات 🎈. كم أصبح معه؟',
            questionEn: 'Sami bought 4 balloons 🎈 then 5 more. How many in total?',
            options: [8, 9, 10],
            correctAnswer: 9,
            explanationAr: '4 + 5 = 9 بالونات ملونة!',
            explanationEn: '4 + 5 = 9 balloons!',
          },
        ],
      },
      {
        id: 'u2_l3',
        unitId: 'unit_2',
        titleAr: 'تاج الجمع الخارق (Boss Quiz)',
        titleEn: 'Addition Master Crown (Boss)',
        descriptionAr: 'تحدي الجمع الملكي للحصول على التاج',
        descriptionEn: 'Royal addition challenge for the crown',
        icon: '👑',
        color: 'amber',
        xpReward: 35,
        starsRequiredToUnlock: 4,
        questions: [
          {
            id: 'u2_l3_q1',
            type: 'multiple_choice',
            questionAr: 'ما ناتج: 7 + 5 = ؟',
            questionEn: 'What is 7 + 5 = ?',
            options: [11, 12, 13],
            correctAnswer: 12,
            explanationAr: '7 + 5 = 12 إجابة متميزة!',
            explanationEn: '7 + 5 = 12 excellent answer!',
          },
          {
            id: 'u2_l3_q2',
            type: 'equation_build',
            questionAr: 'رتب المعادلة: 5 + 4 = 9',
            questionEn: 'Assemble equation: 5 + 4 = 9',
            equationPieces: ['5', '+', '4', '=', '9'],
            targetEquation: ['5', '+', '4', '=', '9'],
            correctAnswer: '5+4=9',
            explanationAr: 'معادلة صحيحة ومتقنة!',
            explanationEn: 'Accurate equation!',
          },
        ],
      },
    ],
  },

  {
    id: 'unit_3',
    unitNumber: 3,
    titleAr: 'أسرار الطرح والإنقاص السحري',
    titleEn: 'Magic Subtraction & Takeaway',
    subtitleAr: 'تعلم إنقاص العناصر ومعرفة الباقي',
    subtitleEn: 'Take away items and find the remainder',
    themeColor: 'rose',
    gradientBg: 'from-rose-500 to-pink-600',
    bannerEmoji: '➖',
    chestReward: {
      id: 'chest_unit_3',
      gems: 40,
      stars: 6,
      titleAr: 'صندوق سحرة الطرح',
      titleEn: 'Subtraction Wizards Chest',
    },
    lessons: [
      {
        id: 'u3_l1',
        unitId: 'unit_3',
        titleAr: 'الطرح البصري البسيط',
        titleEn: 'Visual Subtraction',
        descriptionAr: 'خذ بعض الحلوى واحسب ما تبقى',
        descriptionEn: 'Take away some treats and see what remains',
        icon: '➖',
        color: 'rose',
        xpReward: 15,
        starsRequiredToUnlock: 0,
        questions: [
          {
            id: 'u3_l1_q1',
            type: 'multiple_choice',
            questionAr: 'كان معك 5 قطع حلوى 🍬 وأكلت 2. كم تبقى؟',
            questionEn: 'You had 5 candies 🍬 and ate 2. How many left?',
            options: [2, 3, 4],
            correctAnswer: 3,
            explanationAr: '5 - 2 = 3 قطع حلوى متبقية 🍬🍬🍬',
            explanationEn: '5 - 2 = 3 candies left 🍬🍬🍬',
          },
          {
            id: 'u3_l1_q2',
            type: 'true_false',
            questionAr: 'هل 7 - 3 = 4؟',
            questionEn: 'Is 7 - 3 = 4?',
            options: ['نعم / True', 'لا / False'],
            correctAnswer: 'نعم / True',
            explanationAr: 'نعم! 7 - 3 = 4 صحيح تماماً.',
            explanationEn: 'Yes! 7 - 3 = 4 is correct.',
          },
          {
            id: 'u3_l1_q3',
            type: 'fill_blank',
            questionAr: 'أكمل المسألة: 10 - [ ؟ ] = 6',
            questionEn: 'Complete: 10 - [ ? ] = 6',
            options: [3, 4, 5],
            correctAnswer: 4,
            explanationAr: '10 - 4 = 6 إجابة ذكية!',
            explanationEn: '10 - 4 = 6 smart answer!',
          },
        ],
      },
      {
        id: 'u3_l2',
        unitId: 'unit_3',
        titleAr: 'تاج سيد الطرح (Boss Quiz)',
        titleEn: 'Subtraction Master Crown (Boss)',
        descriptionAr: 'اختبار الطرح النهائي لنيل تاج البراعة',
        descriptionEn: 'Final subtraction test for the crown',
        icon: '👑',
        color: 'amber',
        xpReward: 35,
        starsRequiredToUnlock: 2,
        questions: [
          {
            id: 'u3_l2_q1',
            type: 'match_pairs',
            questionAr: 'طابق كل مسألة طرح بناتجها:',
            questionEn: 'Match each subtraction to its result:',
            correctAnswer: 'matched_all',
            matchingPairs: [
              { id: 'p1', left: '9 - 4', right: '5' },
              { id: 'p2', left: '8 - 2', right: '6' },
              { id: 'p3', left: '10 - 7', right: '3' },
            ],
            explanationAr: 'تطابق رائع وعبقري!',
            explanationEn: 'Awesome matching!',
          },
          {
            id: 'u3_l2_q2',
            type: 'equation_build',
            questionAr: 'رتب معادلة الطرح: 8 - 3 = 5',
            questionEn: 'Build subtraction equation: 8 - 3 = 5',
            equationPieces: ['8', '-', '3', '=', '5'],
            targetEquation: ['8', '-', '3', '=', '5'],
            correctAnswer: '8-3=5',
            explanationAr: 'أنت بطل الطرح الحقيقي!',
            explanationEn: 'You are a true subtraction master!',
          },
        ],
      },
    ],
  },

  {
    id: 'unit_4',
    unitNumber: 4,
    titleAr: 'ممالك الضرب والمجموعات الذكية',
    titleEn: 'Multiplication Kingdoms',
    subtitleAr: 'تعلم تكرار المجموعات وجداول الضرب الممتعة',
    subtitleEn: 'Learn repeated groups and fun multiplication tables',
    themeColor: 'purple',
    gradientBg: 'from-purple-500 to-indigo-600',
    bannerEmoji: '✖️',
    chestReward: {
      id: 'chest_unit_4',
      gems: 50,
      stars: 8,
      titleAr: 'كنز فرسان جدول الضرب',
      titleEn: 'Times Table Knights Chest',
    },
    lessons: [
      {
        id: 'u4_l1',
        unitId: 'unit_4',
        titleAr: 'المجموعات المتكررة (جدول 2 و 3)',
        titleEn: 'Repeated Groups (2s & 3s)',
        descriptionAr: 'احسب عدد العناصر في الأكياس والمجموعات',
        descriptionEn: 'Count items in equal bags and groups',
        icon: '✖️',
        color: 'purple',
        xpReward: 20,
        starsRequiredToUnlock: 0,
        questions: [
          {
            id: 'u4_l1_q1',
            type: 'multiple_choice',
            questionAr: '3 أكياس في كل كيس تفاحتان (3 × 2). كم تفاحة في المجموع؟',
            questionEn: '3 bags with 2 apples each (3 × 2). How many apples total?',
            options: [5, 6, 8],
            correctAnswer: 6,
            explanationAr: '3 × 2 = 6 تفاحات (2 + 2 + 2 = 6)!',
            explanationEn: '3 × 2 = 6 apples (2 + 2 + 2 = 6)!',
          },
          {
            id: 'u4_l1_q2',
            type: 'true_false',
            questionAr: 'هل 4 × 2 = 8؟',
            questionEn: 'Is 4 × 2 = 8?',
            options: ['نعم / True', 'لا / False'],
            correctAnswer: 'نعم / True',
            explanationAr: 'نعم! 4 مكررة مرتين = 8.',
            explanationEn: 'Yes! 4 times 2 = 8.',
          },
          {
            id: 'u4_l1_q3',
            type: 'match_pairs',
            questionAr: 'طابق عمليات الضرب بنواتجها:',
            questionEn: 'Match multiplications to products:',
            correctAnswer: 'matched_all',
            matchingPairs: [
              { id: 'p1', left: '3 × 3', right: '9' },
              { id: 'p2', left: '2 × 5', right: '10' },
              { id: 'p3', left: '4 × 3', right: '12' },
            ],
            explanationAr: 'إتقان تام للضرب!',
            explanationEn: 'Total multiplication mastery!',
          },
        ],
      },
      {
        id: 'u4_l2',
        unitId: 'unit_4',
        titleAr: 'تاج قلعة الضرب (Boss Castle)',
        titleEn: 'Multiplication Castle Boss',
        descriptionAr: 'تحدي عباقرة الضرب ونيل التاج الإمبراطوري',
        descriptionEn: 'Challenge multiplication wizards for the crown',
        icon: '👑',
        color: 'amber',
        xpReward: 40,
        starsRequiredToUnlock: 3,
        questions: [
          {
            id: 'u4_l2_q1',
            type: 'multiple_choice',
            questionAr: 'ما ناتج: 5 × 4 = ؟',
            questionEn: 'What is 5 × 4 = ?',
            options: [15, 20, 25],
            correctAnswer: 20,
            explanationAr: '5 × 4 = 20 إجابة عبقرية سريعة!',
            explanationEn: '5 × 4 = 20 brilliant fast math!',
          },
          {
            id: 'u4_l2_q2',
            type: 'equation_build',
            questionAr: 'ابنِ المعادلة: 3 × 4 = 12',
            questionEn: 'Build: 3 × 4 = 12',
            equationPieces: ['3', '×', '4', '=', '12'],
            targetEquation: ['3', '×', '4', '=', '12'],
            correctAnswer: '3×4=12',
            explanationAr: 'معادلة ضرب مثالية!',
            explanationEn: 'Perfect multiplication equation!',
          },
        ],
      },
    ],
  },

  {
    id: 'unit_5',
    unitNumber: 5,
    titleAr: 'قسمة العدالة والمشاركة',
    titleEn: 'Fair Share & Division',
    subtitleAr: 'وزع بالتساوي واكتشف مفهوم القسمة العادلة',
    subtitleEn: 'Distribute equally and discover fair division',
    themeColor: 'amber',
    gradientBg: 'from-amber-500 to-orange-600',
    bannerEmoji: '➗',
    chestReward: {
      id: 'chest_unit_5',
      gems: 60,
      stars: 10,
      titleAr: 'صندوق حكماء القسمة والعدالة',
      titleEn: 'Wise Division Chest',
    },
    lessons: [
      {
        id: 'u5_l1',
        unitId: 'unit_5',
        titleAr: 'التوزيع العادل بين الأصدقاء',
        titleEn: 'Fair Share among Friends',
        descriptionAr: 'قسم الحلوى والألعاب بالتساوي دون أن يظلم أحد',
        descriptionEn: 'Share candies and toys equally without remainder',
        icon: '➗',
        color: 'amber',
        xpReward: 20,
        starsRequiredToUnlock: 0,
        questions: [
          {
            id: 'u5_l1_q1',
            type: 'multiple_choice',
            questionAr: 'نريد توزيع 6 تفاحات بالتساوي على صديقين (6 ÷ 2). كم يأخذ كل صديق؟',
            questionEn: 'Share 6 apples equally between 2 friends (6 ÷ 2). How many each?',
            options: [2, 3, 4],
            correctAnswer: 3,
            explanationAr: '6 ÷ 2 = 3 تفاحات لكل صديق بالتساوي 🍎🍎🍎',
            explanationEn: '6 ÷ 2 = 3 apples per friend equally 🍎🍎🍎',
          },
          {
            id: 'u5_l1_q2',
            type: 'true_false',
            questionAr: 'هل 8 ÷ 4 = 2؟',
            questionEn: 'Is 8 ÷ 4 = 2?',
            options: ['نعم / True', 'لا / False'],
            correctAnswer: 'نعم / True',
            explanationAr: 'نعم! 8 كرات مقسمة على 4 أصدقاء = 2 كرتان لكل صديق.',
            explanationEn: 'Yes! 8 divided by 4 equals 2.',
          },
          {
            id: 'u5_l1_q3',
            type: 'match_pairs',
            questionAr: 'طابق مسائل القسمة بنواتجها:',
            questionEn: 'Match division problems with results:',
            correctAnswer: 'matched_all',
            matchingPairs: [
              { id: 'p1', left: '10 ÷ 2', right: '5' },
              { id: 'p2', left: '12 ÷ 3', right: '4' },
              { id: 'p3', left: '9 ÷ 3', right: '3' },
            ],
            explanationAr: 'توزيع عادل ومتقن 100%!',
            explanationEn: '100% accurate fair sharing!',
          },
        ],
      },
      {
        id: 'u5_l2',
        unitId: 'unit_5',
        titleAr: 'تاج حكيم الرياضيات الأكبر (Grand Crown)',
        titleEn: 'Grand Math Wizard Crown (Boss)',
        descriptionAr: 'الاختبار الأخير لتصبح ملك عباقرة الرياضيات',
        descriptionEn: 'The ultimate quest to become Grand Math Wizard',
        icon: '👑',
        color: 'yellow',
        xpReward: 50,
        starsRequiredToUnlock: 3,
        questions: [
          {
            id: 'u5_l2_q1',
            type: 'multiple_choice',
            questionAr: 'ما ناتج: 20 ÷ 4 = ؟',
            questionEn: 'What is 20 ÷ 4 = ?',
            options: [4, 5, 6],
            correctAnswer: 5,
            explanationAr: '20 ÷ 4 = 5 عبقري حقيقي!',
            explanationEn: '20 ÷ 4 = 5 true genius!',
          },
          {
            id: 'u5_l2_q2',
            type: 'equation_build',
            questionAr: 'ابنِ معادلة القسمة: 15 ÷ 3 = 5',
            questionEn: 'Build division equation: 15 ÷ 3 = 5',
            equationPieces: ['15', '÷', '3', '=', '5'],
            targetEquation: ['15', '÷', '3', '=', '5'],
            correctAnswer: '15÷3=5',
            explanationAr: 'مبروك! لقد أصبحت ملك عباقرة الرياضيات 👑🌟',
            explanationEn: 'Congratulations! You are the Grand Math Wizard 👑🌟',
          },
        ],
      },
    ],
  },
];

// Initial Daily Quests
export const INITIAL_DAILY_QUESTS: DailyQuest[] = [
  {
    id: 'quest_1',
    titleAr: 'اكسب 30 نقطة خبرة (XP)',
    titleEn: 'Earn 30 XP',
    icon: '⚡',
    progress: 0,
    target: 30,
    xpReward: 15,
    gemReward: 10,
    completed: false,
  },
  {
    id: 'quest_2',
    titleAr: 'أكمل درسين من مسار التعلم',
    titleEn: 'Complete 2 Lessons on Path',
    icon: '📚',
    progress: 0,
    target: 2,
    xpReward: 25,
    gemReward: 15,
    completed: false,
  },
  {
    id: 'quest_3',
    titleAr: 'حقق تقييم 3 نجوم في أي مسألة',
    titleEn: 'Get 3 Stars on any puzzle',
    icon: '⭐',
    progress: 0,
    target: 1,
    xpReward: 20,
    gemReward: 10,
    completed: false,
  },
];

// Mock Live Leaderboard Friends & Competitors
export const INITIAL_LEADERBOARD: LeaderboardUser[] = [
  { id: 'lb_1', name: 'سارة العبقرية', avatar: '👧🏼', xp: 240, rank: 1, streak: 7 },
  { id: 'lb_2', name: 'أحمد البطل', avatar: '👦', xp: 195, rank: 2, streak: 5 },
  { id: 'lb_3', name: 'أنت (البطل)', avatar: '🌟', xp: 85, rank: 3, isCurrentUser: true, streak: 3 },
  { id: 'lb_4', name: 'نور الذكية', avatar: '👧🏻', xp: 70, rank: 4, streak: 2 },
  { id: 'lb_5', name: 'كريم المستكشف', avatar: '🧒', xp: 55, rank: 5, streak: 1 },
  { id: 'lb_6', name: 'ليلى النجمة', avatar: '🌸', xp: 40, rank: 6, streak: 2 },
  { id: 'lb_7', name: 'عمر الطموح', avatar: '🚀', xp: 25, rank: 7, streak: 1 },
];

// Mascot sayings for "فطين" the Duolingo-style Math Owl/Friend
export const MASCOT_QUOTES_AR = [
  'مرحباً يا بطل! هل أنت جاهز لمغامرة الرياضيات اليوم؟ 🦉',
  'الرياضيات لعبة سهلة وممتعة عندما نتخيلها بالأشكال! ✨',
  'كل مسألة تحلها تجعلك أذكى وأقوى! 💪',
  'أنا فخور بك جداً! واصل حماسك وجمع النجوم ⭐',
  'أنت عبقري الرياضيات الصغير! 🌟',
];

export const MASCOT_QUOTES_EN = [
  'Welcome champion! Ready for today’s math adventure? 🦉',
  'Math is easy and fun when we visualize it! ✨',
  'Every puzzle you solve makes you sharper! 💪',
  'I am so proud of you! Keep the streak burning! 🔥',
  'You are a true Math Genius! 🌟',
];
